// <auto-generated />
using System;
using BusStation.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BusStation.Data.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20220203113503_InitDB")]
    partial class InitDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BusStation.Data.DataTransferObjects.Admin.Admin", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("BusStation.Data.Models.Bus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CountOfSeats")
                        .HasColumnType("int");

                    b.Property<string>("Driver")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("Id");

                    b.ToTable("Buses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountOfSeats = 30,
                            Driver = "Petrov Vanya",
                            Name = "Tesla Bus",
                            Number = "1363BM"
                        },
                        new
                        {
                            Id = 2,
                            CountOfSeats = 45,
                            Driver = "Kokorin Ilya",
                            Name = "Transit Bus",
                            Number = "9123BM"
                        },
                        new
                        {
                            Id = 3,
                            CountOfSeats = 25,
                            Driver = "Miller Anton",
                            Name = "Super Bus",
                            Number = "6184BM"
                        },
                        new
                        {
                            Id = 4,
                            CountOfSeats = 50,
                            Driver = "Novikov Evgene",
                            Name = "Audi Bus",
                            Number = "7426BM"
                        },
                        new
                        {
                            Id = 5,
                            CountOfSeats = 25,
                            Driver = "Ignatiev Ignat",
                            Name = "BMW Bus",
                            Number = "7618BM"
                        });
                });

            modelBuilder.Entity("BusStation.Data.Models.BusStop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("BusStops");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Location = "Novopolotsk",
                            Name = "Bus station"
                        },
                        new
                        {
                            Id = 2,
                            Location = "Novopolotsk",
                            Name = "Shopping centre"
                        },
                        new
                        {
                            Id = 3,
                            Location = "Novopolotsk",
                            Name = "Slobodskaya"
                        },
                        new
                        {
                            Id = 4,
                            Location = "Novopolotsk",
                            Name = "Gaidara"
                        },
                        new
                        {
                            Id = 5,
                            Location = "Novopolotsk",
                            Name = "The First Tent"
                        },
                        new
                        {
                            Id = 6,
                            Location = "Novopolotsk",
                            Name = "Golden Field"
                        },
                        new
                        {
                            Id = 7,
                            Location = "Novopolotsk",
                            Name = "Cosmos Cinema"
                        },
                        new
                        {
                            Id = 8,
                            Location = "Novopolotsk",
                            Name = "Youth"
                        },
                        new
                        {
                            Id = 9,
                            Location = "Novopolotsk",
                            Name = "Komsomolskaya"
                        },
                        new
                        {
                            Id = 10,
                            Location = "Novopolotsk",
                            Name = "Music School"
                        },
                        new
                        {
                            Id = 11,
                            Location = "Novopolotsk",
                            Name = "Cinema Minsk"
                        },
                        new
                        {
                            Id = 12,
                            Location = "Novopolotsk",
                            Name = "Naftan Hotel"
                        },
                        new
                        {
                            Id = 13,
                            Location = "Novopolotsk",
                            Name = "Factory Meter"
                        },
                        new
                        {
                            Id = 14,
                            Location = "Novopolotsk",
                            Name = "Podcastels"
                        },
                        new
                        {
                            Id = 15,
                            Location = "Novopolotsk",
                            Name = "Vasilevtsy"
                        },
                        new
                        {
                            Id = 16,
                            Location = "Novopolotsk",
                            Name = "8th Microdistrict"
                        },
                        new
                        {
                            Id = 17,
                            Location = "Novopolotsk",
                            Name = "Polimirovskaya"
                        },
                        new
                        {
                            Id = 18,
                            Location = "Novopolotsk",
                            Name = "Solar"
                        },
                        new
                        {
                            Id = 19,
                            Location = "Novopolotsk",
                            Name = "Meadow"
                        },
                        new
                        {
                            Id = 20,
                            Location = "Novopolotsk",
                            Name = "Ekiman-1"
                        },
                        new
                        {
                            Id = 21,
                            Location = "Novopolotsk",
                            Name = "Ekiman-2"
                        },
                        new
                        {
                            Id = 22,
                            Location = "Polotsk",
                            Name = "Ksta Hospital"
                        },
                        new
                        {
                            Id = 23,
                            Location = "Polotsk",
                            Name = "The Mound of Immortality"
                        },
                        new
                        {
                            Id = 24,
                            Location = "Polotsk",
                            Name = "Ekiman"
                        },
                        new
                        {
                            Id = 25,
                            Location = "Polotsk",
                            Name = "Zapolotye"
                        },
                        new
                        {
                            Id = 26,
                            Location = "Polotsk",
                            Name = "Power supply"
                        },
                        new
                        {
                            Id = 27,
                            Location = "Polotsk",
                            Name = "Sports Club"
                        },
                        new
                        {
                            Id = 28,
                            Location = "Polotsk",
                            Name = "College of Economics"
                        },
                        new
                        {
                            Id = 29,
                            Location = "Novopolotsk",
                            Name = "Hotel Belarus"
                        },
                        new
                        {
                            Id = 30,
                            Location = "Polotsk",
                            Name = "Pedagogical College"
                        },
                        new
                        {
                            Id = 31,
                            Location = "Novopolotsk",
                            Name = "Sewing Factory"
                        },
                        new
                        {
                            Id = 32,
                            Location = "Novopolotsk",
                            Name = "Printing house"
                        },
                        new
                        {
                            Id = 33,
                            Location = "Novopolotsk",
                            Name = "Suvorov"
                        },
                        new
                        {
                            Id = 34,
                            Location = "Novopolotsk",
                            Name = "Leningrad"
                        },
                        new
                        {
                            Id = 35,
                            Location = "Novopolotsk",
                            Name = "Locomotive Depot"
                        },
                        new
                        {
                            Id = 36,
                            Location = "Novopolotsk",
                            Name = "School №14"
                        },
                        new
                        {
                            Id = 37,
                            Location = "Novopolotsk",
                            Name = "Move"
                        },
                        new
                        {
                            Id = 38,
                            Location = "Novopolotsk",
                            Name = "Tchaikovsky"
                        },
                        new
                        {
                            Id = 39,
                            Location = "Novopolotsk",
                            Name = "Griboyedov"
                        },
                        new
                        {
                            Id = 40,
                            Location = "Novopolotsk",
                            Name = "Bagramyan"
                        },
                        new
                        {
                            Id = 41,
                            Location = "Novopolotsk",
                            Name = "Kalinina"
                        },
                        new
                        {
                            Id = 42,
                            Location = "Polotsl",
                            Name = "Manege"
                        },
                        new
                        {
                            Id = 43,
                            Location = "Novopolotsk",
                            Name = "Soyuzpechat"
                        },
                        new
                        {
                            Id = 44,
                            Location = "Polotsk",
                            Name = "Fire Station"
                        },
                        new
                        {
                            Id = 45,
                            Location = "Polotsk",
                            Name = "Matrosova"
                        },
                        new
                        {
                            Id = 46,
                            Location = "Polotsk",
                            Name = "School №18"
                        },
                        new
                        {
                            Id = 47,
                            Location = "Polotsk",
                            Name = "Masherova"
                        },
                        new
                        {
                            Id = 48,
                            Location = "Polotsk",
                            Name = "Partisan"
                        },
                        new
                        {
                            Id = 49,
                            Location = "Polotsk",
                            Name = "Fleet"
                        },
                        new
                        {
                            Id = 50,
                            Location = "Novopolotsk",
                            Name = "Nevelskaya"
                        },
                        new
                        {
                            Id = 51,
                            Location = "Minsk",
                            Name = "Bus station"
                        },
                        new
                        {
                            Id = 52,
                            Location = "Braslav",
                            Name = "Bus station"
                        },
                        new
                        {
                            Id = 53,
                            Location = "Miory",
                            Name = "Bus station"
                        },
                        new
                        {
                            Id = 54,
                            Location = "Brest",
                            Name = "Bus station"
                        },
                        new
                        {
                            Id = 55,
                            Location = "Grodno",
                            Name = "Bus station"
                        },
                        new
                        {
                            Id = 56,
                            Location = "Lida",
                            Name = "Bus station"
                        });
                });

            modelBuilder.Entity("BusStation.Data.Models.Route", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("RouteTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RouteTypeId");

                    b.ToTable("Routes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RouteTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            RouteTypeId = 1
                        },
                        new
                        {
                            Id = 3,
                            RouteTypeId = 2
                        },
                        new
                        {
                            Id = 4,
                            RouteTypeId = 2
                        },
                        new
                        {
                            Id = 5,
                            RouteTypeId = 3
                        },
                        new
                        {
                            Id = 6,
                            RouteTypeId = 3
                        });
                });

            modelBuilder.Entity("BusStation.Data.Models.RouteBusStop", b =>
                {
                    b.Property<int>("RouteId")
                        .HasColumnType("int");

                    b.Property<int>("BusStopId")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("MinutesInWay")
                        .HasColumnType("int");

                    b.Property<int>("WaitingTime")
                        .HasColumnType("int");

                    b.HasKey("RouteId", "BusStopId", "Order");

                    b.HasIndex("BusStopId");

                    b.ToTable("RouteBusStop");

                    b.HasData(
                        new
                        {
                            RouteId = 1,
                            BusStopId = 1,
                            Order = 1,
                            MinutesInWay = 3,
                            WaitingTime = 0
                        },
                        new
                        {
                            RouteId = 1,
                            BusStopId = 4,
                            Order = 2,
                            MinutesInWay = 2,
                            WaitingTime = 0
                        },
                        new
                        {
                            RouteId = 1,
                            BusStopId = 6,
                            Order = 3,
                            MinutesInWay = 10,
                            WaitingTime = 0
                        },
                        new
                        {
                            RouteId = 1,
                            BusStopId = 3,
                            Order = 4,
                            MinutesInWay = 11,
                            WaitingTime = 0
                        },
                        new
                        {
                            RouteId = 1,
                            BusStopId = 11,
                            Order = 5,
                            MinutesInWay = 6,
                            WaitingTime = 0
                        },
                        new
                        {
                            RouteId = 1,
                            BusStopId = 12,
                            Order = 6,
                            MinutesInWay = 3,
                            WaitingTime = 0
                        },
                        new
                        {
                            RouteId = 2,
                            BusStopId = 1,
                            Order = 1,
                            MinutesInWay = 3,
                            WaitingTime = 0
                        },
                        new
                        {
                            RouteId = 2,
                            BusStopId = 7,
                            Order = 2,
                            MinutesInWay = 9,
                            WaitingTime = 0
                        },
                        new
                        {
                            RouteId = 2,
                            BusStopId = 17,
                            Order = 3,
                            MinutesInWay = 3,
                            WaitingTime = 0
                        },
                        new
                        {
                            RouteId = 2,
                            BusStopId = 23,
                            Order = 4,
                            MinutesInWay = 5,
                            WaitingTime = 0
                        },
                        new
                        {
                            RouteId = 3,
                            BusStopId = 31,
                            Order = 1,
                            MinutesInWay = 5,
                            WaitingTime = 0
                        },
                        new
                        {
                            RouteId = 3,
                            BusStopId = 36,
                            Order = 2,
                            MinutesInWay = 21,
                            WaitingTime = 0
                        },
                        new
                        {
                            RouteId = 3,
                            BusStopId = 19,
                            Order = 3,
                            MinutesInWay = 15,
                            WaitingTime = 0
                        },
                        new
                        {
                            RouteId = 4,
                            BusStopId = 46,
                            Order = 1,
                            MinutesInWay = 5,
                            WaitingTime = 0
                        },
                        new
                        {
                            RouteId = 4,
                            BusStopId = 44,
                            Order = 2,
                            MinutesInWay = 4,
                            WaitingTime = 0
                        },
                        new
                        {
                            RouteId = 4,
                            BusStopId = 41,
                            Order = 3,
                            MinutesInWay = 6,
                            WaitingTime = 0
                        },
                        new
                        {
                            RouteId = 4,
                            BusStopId = 42,
                            Order = 4,
                            MinutesInWay = 5,
                            WaitingTime = 0
                        },
                        new
                        {
                            RouteId = 4,
                            BusStopId = 43,
                            Order = 5,
                            MinutesInWay = 3,
                            WaitingTime = 0
                        },
                        new
                        {
                            RouteId = 5,
                            BusStopId = 53,
                            Order = 1,
                            MinutesInWay = 90,
                            WaitingTime = 10
                        },
                        new
                        {
                            RouteId = 5,
                            BusStopId = 52,
                            Order = 2,
                            MinutesInWay = 40,
                            WaitingTime = 10
                        },
                        new
                        {
                            RouteId = 6,
                            BusStopId = 54,
                            Order = 1,
                            MinutesInWay = 120,
                            WaitingTime = 30
                        },
                        new
                        {
                            RouteId = 6,
                            BusStopId = 55,
                            Order = 2,
                            MinutesInWay = 110,
                            WaitingTime = 30
                        },
                        new
                        {
                            RouteId = 6,
                            BusStopId = 56,
                            Order = 3,
                            MinutesInWay = 120,
                            WaitingTime = 30
                        });
                });

            modelBuilder.Entity("BusStation.Data.Models.RouteType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RouteTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Urban"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Suburban"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Intercity"
                        });
                });

            modelBuilder.Entity("BusStation.Data.Models.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Schedules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Even days"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Odd days"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Everyday"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Weekend"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Weekdays"
                        });
                });

            modelBuilder.Entity("BusStation.Data.Models.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BusId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("RouteId")
                        .HasColumnType("int");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BusId");

                    b.HasIndex("RouteId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("Trips");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BusId = 1,
                            DepartureTime = new DateTime(1, 1, 1, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            RouteId = 2,
                            ScheduleId = 5
                        },
                        new
                        {
                            Id = 2,
                            BusId = 1,
                            DepartureTime = new DateTime(1, 1, 1, 18, 30, 0, 0, DateTimeKind.Unspecified),
                            RouteId = 1,
                            ScheduleId = 5
                        },
                        new
                        {
                            Id = 3,
                            BusId = 3,
                            DepartureTime = new DateTime(1, 1, 1, 14, 20, 0, 0, DateTimeKind.Unspecified),
                            RouteId = 2,
                            ScheduleId = 4
                        },
                        new
                        {
                            Id = 4,
                            BusId = 2,
                            DepartureTime = new DateTime(1, 1, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            RouteId = 5,
                            ScheduleId = 3
                        },
                        new
                        {
                            Id = 5,
                            BusId = 1,
                            DepartureTime = new DateTime(1, 1, 1, 15, 25, 0, 0, DateTimeKind.Unspecified),
                            RouteId = 2,
                            ScheduleId = 4
                        });
                });

            modelBuilder.Entity("BusStation.Data.Models.TripReport", b =>
                {
                    b.Property<string>("BusDriver")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BusId")
                        .HasColumnType("int");

                    b.Property<string>("BusName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountOfSeats")
                        .HasColumnType("int");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("RouteId")
                        .HasColumnType("int");

                    b.Property<int>("RouteTypeId")
                        .HasColumnType("int");

                    b.Property<string>("RouteTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int");

                    b.Property<int>("ScheduleName")
                        .HasColumnType("int");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.ToView("View_TripReport");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("BusStation.Data.Models.Route", b =>
                {
                    b.HasOne("BusStation.Data.Models.RouteType", "RouteType")
                        .WithMany()
                        .HasForeignKey("RouteTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RouteType");
                });

            modelBuilder.Entity("BusStation.Data.Models.RouteBusStop", b =>
                {
                    b.HasOne("BusStation.Data.Models.BusStop", "BusStop")
                        .WithMany("RouteBusStops")
                        .HasForeignKey("BusStopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusStation.Data.Models.Route", "Route")
                        .WithMany("RouteBusStops")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusStop");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("BusStation.Data.Models.Trip", b =>
                {
                    b.HasOne("BusStation.Data.Models.Bus", "Bus")
                        .WithMany("Trips")
                        .HasForeignKey("BusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusStation.Data.Models.Route", "Route")
                        .WithMany()
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusStation.Data.Models.Schedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bus");

                    b.Navigation("Route");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BusStation.Data.DataTransferObjects.Admin.Admin", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BusStation.Data.DataTransferObjects.Admin.Admin", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusStation.Data.DataTransferObjects.Admin.Admin", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BusStation.Data.DataTransferObjects.Admin.Admin", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BusStation.Data.Models.Bus", b =>
                {
                    b.Navigation("Trips");
                });

            modelBuilder.Entity("BusStation.Data.Models.BusStop", b =>
                {
                    b.Navigation("RouteBusStops");
                });

            modelBuilder.Entity("BusStation.Data.Models.Route", b =>
                {
                    b.Navigation("RouteBusStops");
                });
#pragma warning restore 612, 618
        }
    }
}
